In [2]:
import torch
import numpy as np 
import pandas as pd

## introduction to tensor


#### you can refer to the documentation for tensor class present in pytorch module : https://pytorch.org/docs/stable/tensors.html 

### scalar

In [3]:
scalar = torch.tensor(21)
scalar # will return the type as well

tensor(21)

In [4]:
#item will provide the value present in the tensor while ndim is for dimension
#item onnly woks with the scalar
print(scalar.item())
print(scalar.ndim)
print(scalar.shape)

21
0
torch.Size([])


### vector

In [5]:
vector = torch.tensor([21,27])
vector

tensor([21, 27])

##### here dimension will return the number of close square brackets while shape provides the info about the total elements present in the tensor and brackets define how elements are structred


In [6]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


### MATRIX

In [7]:
MATRIX = torch.tensor([[1,2],[3,4]])
MATRIX

tensor([[1, 2],
        [3, 4]])

In [8]:
print(MATRIX.ndim)
print(MATRIX.shape)

2
torch.Size([2, 2])


### Tensor

In [9]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])


### Random Tensors

Why random tensors?

Random tensors are important because the way many neural network learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers ->look at data -> update random numbers`

In [10]:
#create a random tensors of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2528, 0.5426, 0.9170, 0.4929],
        [0.2680, 0.8803, 0.4966, 0.1896],
        [0.4287, 0.5366, 0.8964, 0.3721]])

In [11]:
#create a random tensor with similar shape to as image tensor
tensor_with_image_shape = torch.rand(size=(3,28,28)) # color chennel, height, width ,size parameter is optional
tensor_with_image_shape,tensor_with_image_shape.ndim

(tensor([[[0.1247, 0.1268, 0.4548,  ..., 0.8467, 0.1317, 0.3091],
          [0.1705, 0.1210, 0.0304,  ..., 0.6618, 0.1595, 0.6966],
          [0.9642, 0.5009, 0.5330,  ..., 0.0101, 0.7593, 0.4500],
          ...,
          [0.3311, 0.4599, 0.0057,  ..., 0.8361, 0.4290, 0.2294],
          [0.9006, 0.1077, 0.9066,  ..., 0.9922, 0.7991, 0.4940],
          [0.4178, 0.8699, 0.8969,  ..., 0.1312, 0.5756, 0.1825]],
 
         [[0.2305, 0.8898, 0.1126,  ..., 0.4450, 0.4753, 0.3440],
          [0.8471, 0.7993, 0.4827,  ..., 0.4897, 0.1314, 0.4755],
          [0.7852, 0.7395, 0.2421,  ..., 0.3435, 0.5295, 0.9541],
          ...,
          [0.2529, 0.2202, 0.3198,  ..., 0.2494, 0.4161, 0.7927],
          [0.8731, 0.5762, 0.0758,  ..., 0.9935, 0.0889, 0.6626],
          [0.4263, 0.3962, 0.3388,  ..., 0.1045, 0.6404, 0.3288]],
 
         [[0.2891, 0.6762, 0.0530,  ..., 0.6277, 0.4623, 0.7298],
          [0.3441, 0.8908, 0.5025,  ..., 0.2644, 0.4042, 0.5142],
          [0.6949, 0.3049, 0.6819,  ...,

### Zeroes and Ones

In [12]:
#tensor containing all zeroes and also used as mask
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [13]:
#mask using
rt = torch.rand(size=(3,4))
ft = rt*zeros
ft

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [14]:
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [15]:
print(zeros.dtype)
print(ones.dtype)


torch.float32
torch.float32


### Creating a tensor range and tensor like

In [16]:
tensor_with_range = torch.arange(start=1,end=11,step=2)
tensor_with_range

tensor([1, 3, 5, 7, 9])

In [17]:
#tensor like
new_tensor = torch.ones_like(input=tensor_with_range) #zeros like
new_tensor

tensor([1, 1, 1, 1, 1])

### tensor datatype

<b>Note</b> : Tensor datatypes is one of the 3 big errors you'll run into with pytorch and deep learning

<ol>
<li>Tensors not right datatype</li>
<li>Tensors not right shape</li>
<li>Tensors not on the right device</li>
</ol>

In [18]:
#float 32 tensor
# by default the datatype of each tensor created is float32
#32 and 16 is about precision
float_32_tensor = torch.tensor([1.0,2.0,3.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device=None, # what device is your tensor on
                               requires_grad=False # whether or not to track gradients with this tensors operations
                               ) 
float_32_tensor.dtype

torch.float32

In [19]:
float_16_tensor = float_32_tensor.type(torch.float16)

In [20]:
float_16_tensor

tensor([1., 2., 3.], dtype=torch.float16)

In [21]:
float_16_tensor*float_32_tensor

tensor([1., 4., 9.])

### Getting information from tensors
<ol>
<li>Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`</li>
<li>Tensors not right shape - to get shape from a tensor, can use `tensor.shape`</li>
<li>Tensors not on the right device - to get device from a tensor, can use `tensor.device`</li>
</ol>

In [22]:
some_tensor = torch.tensor([1,2,3])
print(some_tensor)
print(f"datatype of the tensor is {some_tensor.dtype}")
print(f"the device on which the tensor is : {some_tensor.device}")
print(f"the shape of the tensor is : {some_tensor.shape}")

tensor([1, 2, 3])
datatype of the tensor is torch.int64
the device on which the tensor is : cpu
the shape of the tensor is : torch.Size([3])


### Manipulating tensors (tensor operation)

Tensor operation includes:
<ul>
<li>Addition</li>
<li>Subtraction</li>
<li>Multiplication (element wise)</li>
<li>Division</li>
<li>Matrix multiplication</li>
</ul>

In [23]:
#Addition, subtraction, multiplication, division
tensor = torch.tensor([1,2,3])
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [24]:
#using in built function present in torch library mul,sub,mul,div 
tensor = torch.sub(tensor,5)
tensor

tensor([-14, -13, -12])

### Matrix Multiplication

two main ways of performing multiplication in neural networks and deep learning 
1. Element wise multiplication
2. Matrix multiplication (dot product)

In [25]:
tensor =  torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [26]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([4,5,6])
print(f"normal multiplication : {t1*t2}")
print(f"with matrix multiplication : {torch.matmul(t1,t2)}") # it takes very less time to execute with comparison of normal multiplication
#here writing mm would also be fine it's an alias of matmul

normal multiplication : tensor([ 4, 10, 18])
with matrix multiplication : 32


<p style="color:green">when two matrix are multiplied the main condition is that the inner dimension of them should be equal and resultant matrix will be of outer dimension.
that is why the concept of transposing a matrix will be in picture.</p>
Just visualize,visualize,visualize

In [27]:
tensor_a = torch.rand(size=(2,3))
tensor_b = torch.rand(size=(2,3))
print(tensor_a)
print(tensor_b)
print(tensor_b.T)
print(torch.mm(tensor_a,tensor_b.T))

print(tensor_a.shape)
print(tensor_b.shape)
print(tensor_b.T.shape)


tensor([[0.1649, 0.8245, 0.3910],
        [0.8688, 0.8200, 0.8884]])
tensor([[0.4307, 0.6399, 0.7287],
        [0.5061, 0.7511, 0.0276]])
tensor([[0.4307, 0.5061],
        [0.6399, 0.7511],
        [0.7287, 0.0276]])
tensor([[0.8836, 0.7135],
        [1.5463, 1.0802]])
torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([3, 2])


### finding the min,max,mean,sum, etc (tensor aggregation)

In [28]:
#creating a tensor
t = torch.arange(start=1,end=50,step=5)
t

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [29]:
torch.min(t),torch.max(t)
#or
t.min(),t.max()

(tensor(1), tensor(46))

In [30]:
#here torch.mean() function requires a tensor of float32 datatype to work but the datatype of "t" is Long here
# t.mean()
t.type(torch.float32).mean()

tensor(23.5000)

### find the positional min and max

In [31]:
t = torch.arange(start=1,end=50,step=5)
t

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [32]:
t.argmax(),t.argmin()
#or
torch.argmax(t),torch.argmin(t)

(tensor(9), tensor(0))

### Reshaping, stacking, squeezing and unsqueezing tensors

<ul>
<li><b>Reshaping</b> reshapes an input tensor to a defined shape</li>
<li><b>View</b> Returns a view of an input tensor of certain shape but keep the same memory as the original tensor</li>
<li><b>Stacking</b> combine multiple tensors on top of each other (vstack) or side by side (hstack)</li>
<li><b>Squeeze</b> removes all <code>1</code> dimensions from a tensor</li>
<li><b>Unsqueeze</b> add a <code>1</code> dimension to a target tensor</li>
<li><b>Permute</b> return a view of the input with dimensions permuted (swapped) in a certain way</li>
</ul>

In [33]:
x= torch.arange(1,10,1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
#reshaping takes place only when the multiplication of reshaping dimension equals to number of elements 
print(x.shape)
x_reshaped = x.reshape(3,3) #possibilities (1,9),(9,1)
print(x_reshaped)

torch.Size([9])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [35]:
#change the view
z = x.view(3,3)
print(z)
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [36]:
#changes z changes x (because a view of a tensor shares the same memory as the original input)
z[1,1]=3
print(z)
print(x)

tensor([[1, 2, 3],
        [4, 3, 6],
        [7, 8, 9]])
tensor([1, 2, 3, 4, 3, 6, 7, 8, 9])


In [37]:
#torch.squeeze() - removes all single dimension from a target tensor
t = torch.rand(size=(3,4))
print(t)
t = t.reshape(1,3,4)
print("t reshaped : ",t)

print(t.shape)
t = t.squeeze()
print(f"after applying the squeeze function shape of tensor would be : {t.shape}") 


tensor([[0.0904, 0.3827, 0.2057, 0.1317],
        [0.5649, 0.4151, 0.6709, 0.0090],
        [0.9112, 0.6689, 0.7902, 0.9878]])
t reshaped :  tensor([[[0.0904, 0.3827, 0.2057, 0.1317],
         [0.5649, 0.4151, 0.6709, 0.0090],
         [0.9112, 0.6689, 0.7902, 0.9878]]])
torch.Size([1, 3, 4])
after applying the squeeze function shape of tensor would be : torch.Size([3, 4])


In [38]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim
print(f"previous target : {t}")
print(f"previous sahpe : {t.shape}")

#add an extra dimension with unsqueeze
t = t.unsqueeze(dim=2)
print(f"\nnew tensor : {t}")
print(f"new tensor shape : {t.shape}")


previous target : tensor([[0.0904, 0.3827, 0.2057, 0.1317],
        [0.5649, 0.4151, 0.6709, 0.0090],
        [0.9112, 0.6689, 0.7902, 0.9878]])
previous sahpe : torch.Size([3, 4])

new tensor : tensor([[[0.0904],
         [0.3827],
         [0.2057],
         [0.1317]],

        [[0.5649],
         [0.4151],
         [0.6709],
         [0.0090]],

        [[0.9112],
         [0.6689],
         [0.7902],
         [0.9878]]])
new tensor shape : torch.Size([3, 4, 1])


In [39]:
#torch.permute - rearranges the dimensions of a target tensor in a specified order 
#image matrix would be the best example here

image = torch.rand(size=(224,224,3))
print(image.size())

image_permuted = torch.permute(image,(2,0,1)) # it indicates the dimension present in main tensor
print(image_permuted.size())


torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [40]:
image[0,0,0] = 2127
image_permuted[0,0,0]

tensor(2127.)

In [41]:
x_stacked = torch.stack([x,x,x,x],dim=0)
print(x_stacked)
x_stacked = torch.stack([x,x,x,x],dim=1)
print(x_stacked)

tensor([[1, 2, 3, 4, 3, 6, 7, 8, 9],
        [1, 2, 3, 4, 3, 6, 7, 8, 9],
        [1, 2, 3, 4, 3, 6, 7, 8, 9],
        [1, 2, 3, 4, 3, 6, 7, 8, 9]])
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [3, 3, 3, 3],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])


In [42]:
x_stacked = torch.hstack([x,x,x,x]) #stacking horizontally will take all the element in single dimension of single tensor
x_stacked

tensor([1, 2, 3, 4, 3, 6, 7, 8, 9, 1, 2, 3, 4, 3, 6, 7, 8, 9, 1, 2, 3, 4, 3, 6,
        7, 8, 9, 1, 2, 3, 4, 3, 6, 7, 8, 9])

### Indexing (selecting data from tensors)

#### Indexing with PyTorch is similar ro indexing with NumPy


In [43]:
x= torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [44]:
# let's index on our new tensor
print(x[0])
print(x[0][0])   # can also be written as [0,0]
print(x[0][0][0].item()) # [0,0,0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor([1, 2, 3])
1


In [45]:
x[0,:,2]


tensor([3, 6, 9])

In [91]:
for i in range(len(x[0])):
    print(x[:,i,i].item(),end=" ")

1 5 9 

### PyTorch tensors & NumPy
##### Numpy is a popular scentific Python numeric computing library.
##### And because of this, PyTorch  has functionality to interect with it.

<ul>
<li>Data in NumPy, want in PyTorch tensor -> <code>torch.from_numpy(ndarray)</code></li>
<li>PyTorch tensor -> NumPy-> <code>torch.Tensor.numpy()</code></li>
</ul>

In [92]:
import numpy

In [93]:
#numpy array to tensor
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # here pytorch reflects numpy's default datatype unless specified  
 
array,tensor
 

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [97]:
array.dtype,tensor.dtype


(dtype('float64'), torch.float64)

Note : numpy_array->float64, tensor->float32

In [96]:
torch.arange(1.0,8.0).dtype

torch.float32

In [98]:
#change the value of array what will this do to tensor and same process will be done when change the value of tensor and nothing will be done to array
array = array + 1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [99]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns: start with random number -> tensor operations -> update random numbers to try and make them better representarions of the data -> again -> again -> again...

In [46]:
t1 = torch.rand(size=(3,4))
t2 = torch.rand(size=(3,4))

print(t1)
print(t2)
print(t1 == t2)

tensor([[0.0296, 0.4118, 0.8883, 0.8545],
        [0.1284, 0.8238, 0.5979, 0.5093],
        [0.0207, 0.2533, 0.2998, 0.3486]])
tensor([[0.1747, 0.0673, 0.8090, 0.1598],
        [0.6136, 0.5560, 0.4306, 0.6005],
        [0.2915, 0.5747, 0.9349, 0.5253]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [49]:
#manual seed will create random but reproducable tensors 
#agenda of random seed is to use same random numbers everytime while executing the code 
#f you want same random number in new defined tensor then you have to write code(torch.manual_seed()) before defining a new t ensor 
random_seed = 42

torch.manual_seed(random_seed)
t1 = torch.rand(size=(3,4))
torch.manual_seed(random_seed)
t2 = torch.rand(size=(3,4))

print(t1)
print(t2)
print(t1 == t2)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## GPUs - makes computing faster
fast computation on numbers, thanks to CUDA + NVIDIA hardware + pytorch working behind the scene to make everything hunky dory(good).


In [51]:
#check for gpu access with pytorch
torch.cuda.is_available()

False

In [53]:
#setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device
#cuda is computation toolkit provided by nvidia, it is for fast computation

'cpu'

In [55]:
#count the number of gpus
torch.cuda.device_count()

0

In [ ]:
# taking tansor OR model to gpu
# define a device, define a tensor, and take tensor to the device defined 
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.rand(size=(1,5))
tensor_on_gpu = tensor.to(device)

# another simple method of checking weather the tensor is on gpu or cpu is that you can convert tensor to numpy array 
# If tensor is on GPU, can't transform it to numpy
# from that point you can move your tensor to cpu
tensor_on_cpu = tensor

<code>tensor_on_gpu.numpy() will lead to typeError if tensor_on_gpu is on gpu</code>

To fix the GPU tensor with numpy issue, we can first set it to the CPU

<code>tensor_on_cpu = tensor_on_gpu.cpu()</code>

<code>tensor_on_cpu.numpy()</code> will work fine

