# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



A [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch.Tensor "torch.Tensor") is a multi-dimensional matrix containing elements of a single data type.
CUDA is a programming model and computing toolkit developed by NVIDIA

In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(size=(7,7))
random_tensor

tensor([[0.4452, 0.3913, 0.8108, 0.1806, 0.1462, 0.6406, 0.5360],
        [0.2766, 0.3205, 0.8258, 0.8033, 0.8338, 0.1557, 0.7903],
        [0.1701, 0.6773, 0.5865, 0.6447, 0.1829, 0.2475, 0.6896],
        [0.3679, 0.4504, 0.8347, 0.5276, 0.4606, 0.1130, 0.4641],
        [0.2853, 0.7936, 0.1030, 0.7608, 0.8314, 0.7250, 0.9511],
        [0.1368, 0.6935, 0.9567, 0.4837, 0.6304, 0.5136, 0.0093],
        [0.3053, 0.3992, 0.9830, 0.7695, 0.0811, 0.3286, 0.4793]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
another_random_tensor = torch.rand(size=(1,7))
# Perform matrix multiplication 
another_random_tensor = another_random_tensor.T
mat_multiplication = torch.mm(random_tensor,another_random_tensor)
mat_multiplication


tensor([[1.6179],
        [2.2497],
        [1.5320],
        [1.8031],
        [2.1707],
        [1.9087],
        [1.7091]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [10]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)

# Create two random tensors
random_tensor1 = torch.rand(size=(7,7))

random_tensor2 = torch.rand(size=(7,1))

# Matrix multiply tensors
output = torch.matmul(random_tensor1,random_tensor2)
output

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [11]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [23]:
# Set random seed
random_seed = 1234

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"device : {device}")
# Create two random tensors on GPU
torch.manual_seed(random_seed)
t1 = torch.rand(size=(2,3)).to(device=device)

t2 = torch.rand(size=(2,3)).to(device=device)

t1,t2

device : cpu


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]]),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]]))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_A and tensor_B
mm = torch.matmul(t1,t2.T)
print(mm)
print(mm.device)
print(mm.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]])
cpu
torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(mm.max())

# Find min
print(mm.min())


tensor(0.5617)
tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max
print(mm.argmax())


# Find arg min
print(mm.argmin())



tensor(3)
tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [27]:
# Set seed
torch.manual_seed(7)

# Create random tensor
random_tensor = torch.rand(size=(1,1,1,10))

# Remove single dimensions
new_tensor = random_tensor.squeeze()

# Print out tensors and their shapes
random_tensor,random_tensor.shape,new_tensor,new_tensor.shape


(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))